apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
bases:
- https://github.com/argoproj/argo-cd/manifests/base/notification?ref=v2.3.17
# - github.com/argoproj-labs/argocd-notifications/manifests/controller?ref=v1.1.1
